import type { Metadata } from "next";
import localFont from "next/font/local";
import { Barlow } from "next/font/google";
import SplashScreen from "@/components/splash-screen";
import PageTransition from "@/components/page-transition";
import "./globals.css";

const mango_grotesque_semibold = localFont({
  src: "/fonts/MangoGrotesque-SemiBold.woff2",
  variable: "--font-mango-grotesque-semibold",
});

const mango_grotesque_regular = localFont({
  src: "/fonts/MangoGrotesque-Regular.woff2",
  variable: "--font-mango-grotesque-regular",
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "KRAY KREATIV3",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${mango_grotesque_regular.variable} ${mango_grotesque_semibold.variable} ${barlow.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SplashScreen>
          <PageTransition>{children}</PageTransition>
        </SplashScreen>
      </body>
    </html>
  );
}
